g49/g49/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from login_logout.views import homepage
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login_logout/', include('login_logout.urls', namespace="login_logout")),
    url(r'^notes/', include('notes.urls',namespace="notes")),
    url(r'^$', homepage,name='homepage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

g49/notes/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url(r'^hello/', views.hello, name='hello'),
    url(r'^enternoteform/', views.enterNoteform, name='enterNoteform'),
    url(r'^printNote/', views.enterNote, name='printNote'),
    url(r'^displaynote/(\d+)/', views.displayNote, name='displaynote'),
    #
    url(r'^searchTag/(\w+)/', views.searchTag, name = 'searchTag'),
    #
    url(r'^editNoteform/(\d+)/', views.editNoteform, name = 'editNoteform'),
    url(r'^editNote/(\d+)/', views.editNote, name = 'editNote'),
    url(r'^deleteNote/(\d+)/', views.deleteNote, name = 'deleteNote'),
    url(r'^searchNote/', views.searchNote, name='searchNote'),
    #url(r'^search/', views.search, name='search'),
    url(r'^alltags/', views.AllTags, name = 'AllTags'),
    #
    url(r'^image/', views.Image, name = 'Image'),
    url(r'^saved/', views.Display, name = 'Display'),
    #url(r'^saved/', views.saved, name = 'Display')
    url(r'^upload/', views.uploadDocument, name = 'upload'),
    url(r'^savedoc/', views.saveDoc, name='saveDoc'),
    url(r'^listdocs/$', views.listDocs, name='listdoc'),
    #
    url(r'^calendar/(\d+)/(\d+)', views.calendarof, name='calendarof'),
    url(r'^calendar/', views.calendar, name='calendar'),
    #
    url(r'^enterevent/', views.enterEventForm, name='enterevent'),
    url(r'^saveEvent/', views.saveEvent, name='saveEvent'),
    #
    url(r'^editEventform/(\d+)/', views.editEventform, name = 'editEventform'),
    url(r'^editEvent/(\d+)/', views.editEvent, name = 'editEvent'),
    url(r'^deletEvent/(\d+)/', views.deleteEvent, name = 'deleteEvent'),
    url(r'^allevents/', views.allevents, name='allevents'),
    #url(r'^searchNote/', views.searchNote, name='searchNote'),
    #
    url(r'^deleteDoc/(\d+)/', views.deleteDoc, name = 'deleteDoc'),
]

g49/notes/models.py
from django.db import models
from login_logout.models import UserInfo
from django.db.models import ImageField, signals
from django.contrib.auth.models import Permission, User
##
from calendar import HTMLCalendar
from datetime import date
from itertools import groupby
from django.utils.html import conditional_escape as esc
from datetime import datetime, timedelta
import os
############## NOTES ################## 
class Notes(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Tag = models.CharField(max_length=20)
	Note = models.TextField()
	my_date = models.DateTimeField(default=datetime.now())
	modified_date = models.DateTimeField(default=datetime.now())

	def __str__(self):
		return self.UserName
############### EVents module ##########
class Event(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Tag = models.CharField(max_length=10)
	Description = models.TextField(max_length=100)
	#event_date = models.DateField()
	my_date = models.DateTimeField(default=datetime.now() + timedelta(days=1))
	start_date = models.DateField()
	end_date = models.DateField()

	def __str__(self):
		return self.UserName
################ FILE HANDELING ####################
class Images(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Image_tag = models.CharField(max_length = 50)
	Image = models.ImageField(upload_to='images/')

	def __str__(self):
		return self.Image_tag
############### Document ###################
class Document(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	docfile = models.FileField(upload_to='')
	#size =
	my_date = models.DateTimeField(default=datetime.now())
	modified_date = models.DateTimeField(default=datetime.now())
	#name, extension = (docfile.name).split(".")
	#name = docfile.name
	#extension = os.path.splitext(name)[1][1:]
	def extension(self):
		name, extension = os.path.splitext(self.docfile.name)
		return extension[1:]
	def name(self):
		name, extension = os.path.splitext(self.docfile.name)
		return name
	#def __str__(self):
	#	return self.docfile
################# HTML Calender #####################
class WorkoutCalendar(HTMLCalendar):
	def __init__(self, workouts):
		super(WorkoutCalendar, self).__init__()
		self.workouts = self.group_by_day(workouts)
	def formatday(self, day, weekday):
		if day != 0:
			cssclass = self.cssclasses[weekday]
			if date.today() == date(self.year, self.month, day):
				cssclass += ' today'
			if day in self.workouts:
				cssclass += ' filled'
				body = ['<ul>']
				for workout in self.workouts[day]:
					body.append('<li>')
					#body.append('<a href="%s">' % workout.get_absolute_url())
					body.append(esc(workout.Tag))
					body.append('</li>')
				body.append('</ul>')
				return self.day_cell(cssclass, '%d' % day)
			return self.day_cell(cssclass, day)
		return self.day_cell('noday', '&nbsp;')

	def formatmonth(self, year, month):
		self.year, self.month = year, month
		return super(WorkoutCalendar, self).formatmonth(year, month)

	def group_by_day(self, workouts):
		field = lambda workout: workout.start_date.day
		return dict(
			[(day, list(items)) for day, items in groupby(workouts, field)]
		)

	def day_cell(self, cssclass, body):
		return '<td class="%s">%s</td>' % (cssclass,body)

g49/notes/forms.py
from django import forms
from django.contrib.auth.models import User
#from django.contrib.admin.widgets import AdminDateWidget
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.admin import widgets                                       


from .models import *

class Note(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['Tag', 'Note']
################ Event Form #################
class EventForm(forms.ModelForm):
    #event_date = forms.DateField(widget=SelectDateWidget)
    start_date = forms.DateField(widget=SelectDateWidget)
    end_date = forms.DateField(widget=SelectDateWidget)
    class Meta:
        model = Event
        fields = ['Tag', 'Description']
        #fields[2].widget = widgets.AdminSplitDateTime()

class EventDateEditForm(forms.Form):
    #event_date = forms.DateField(widget=SelectDateWidget)
    start_date = forms.DateField(widget=SelectDateWidget)
    end_date = forms.DateField(widget=SelectDateWidget)
    
    
################ FILE HANDELING ####################
class ImageForm(forms.ModelForm):
    class Meta:
       model = Images
       fields = ['Image_tag', 'Image']

class DocumentForm(forms.ModelForm):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )
    class Meta:
        model = Document
        fields = ['docfile']
           

g49/notes/views.py
#import utils
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from notes.forms import *
from .models import *
from django.contrib.auth.models import User
from django.utils import timezone#, generic_search
#from django.urls import reverse
from django.core.urlresolvers import reverse
##
from django.shortcuts import render_to_response,redirect
from django.utils.safestring import mark_safe
from datetime import datetime
from .models import WorkoutCalendar,Event
#from haystack.generic_views import SearchView
#from utils import generic_search
################ Custom Views #########################
# used for creating Note form
def enterNoteform(request):
	if request.user.is_authenticated():
		form = Note()
		return render(request, 'enterNote.html', {"form":form})
	else:
		return redirect('login_logout:index')	
# enter a Note that need to be saved
def enterNote(request):
	if request.user.is_authenticated():
		if request.method == "POST":
			form = Note(request.POST)
			if form.is_valid():
				username = request.user.username
				UserName = User.objects.get(username=username)
				tag = form.cleaned_data['Tag']
				note = form.cleaned_data['Note']
				newNote = Notes(UserName = UserName ,Tag = tag, Note = note)
				#newNote = Notes(Tag = tag, Note = note)
				newNote.save()
				#context = {'Tag' : tag, 'Note' : note,}
				return redirect('notes:AllTags')
			else:
				form = Note()
		return render(request, 'enterNote.html', {"form" : form})
	else:
		return redirect('login_logout:index')
# Editing a Note
def editNoteform(request, id):
	if request.user.is_authenticated():
		note = Notes.objects.get(UserName=request.user,pk=id)
		return render(request, 'editNoteform.html',  {"note" : note})
	else:
		return redirect('login_logout:index')
# save edited note
def editNote(request, id):
	if request.user.is_authenticated():
		if request.method == "POST":
			form = Note(request.POST)
			if form.is_valid():
				note = Notes.objects.get(UserName=request.user,pk=id)
				note.Tag = form.cleaned_data['Tag']
				note.Note = form.cleaned_data['Note']
				note.modified_date = datetime.now()
				note.save()
				#context = {'Tag' : tag, 'Note' : note,}
				#return render(request, 'index.html',)
				return redirect('notes:AllTags')
			else:
				note = Notes.objects.get(UserName=request.user,pk=id)
		return render(request, 'editNoteform.html',  {"note" : note})
	else:
		return redirect('login_logout:index')	
# Deleting a Note
def deleteNote(request, id):
	if request.user.is_authenticated():
		Notes.objects.get(UserName=request.user,pk=id).delete()
		#return HttpResponse("done")
		return redirect('notes:AllTags')
	else:
		return redirect('login_logout:index')	
# Printing all notes under the user
def AllTags(request):
	if request.user.is_authenticated():
		username = request.user.username
		username = User.objects.get(username=username)
		notes = Notes.objects.filter(UserName = username)
		return render(request, 'note.html', {"notes" : notes})
	else:
		return redirect('login_logout:index')
def displayNote(request, id):
	if request.user.is_authenticated():
		note = Notes.objects.get(UserName=request.user,pk=id)
		return render(request, 'printNote.html', {'note' : note})
	else:
		return redirect('login_logout:index')
# Serch a tag given after URL : searchTag/"."
def searchTag(request, tag):
	if request.user.is_authenticated():
		objects = Notes.objects.filter(UserName=request.user,Tag = tag)
		ob ='Printing all Notes with Tag : %s in the DB : <br>'%(tag)
		for tag in objects:
			ob += tag.Note+"<br>"

		return HttpResponse(ob)
	else:
		return redirect('login_logout:index')
# Search Note using Tag from GET request(Partial search accepted)
def searchNote(request):
	if request.user.is_authenticated():
		q = request.GET.get('q', None)
		if q:
			username = request.user.username
			username = User.objects.get(username=username)
			notes = Notes.objects.filter(UserName=username, Tag__contains=q)
			return render(request, 'search.html', {'notes' : notes})
		return HttpResponse("Search Empty")
	else:
		return redirect('login_logout:index')
# Search that search all fields of all models for that object which we have passed as search object
MODEL_MAP = { Notes: ["UserName","Tag","Note","my_date","modified_date"],
              Event  : ["UserName","Tag","Description","event_date","my_date","start_date","end_date",],
            }
# def search(request):
	# objects = []
	# for model,fields in MODEL_MAP.iteritems():
		# objects+=generic_search(request,model,fields,)
		# return render_to_response("search_result.html",
                                 # {"objects":objects,
                                  # "search_string" : request.GET.get('q',""),
                              # }
       # )

	# return HttpResponse("Search Empty")
####################################################
################ Event Scheduling ##################
####################################################
def enterEventForm(request):
	if request.user.is_authenticated():	
		form = EventForm()
		return render(request, 'enter_event.html', {"form":form})
	else:
		return redirect('login_logout:index')
# save event
def saveEvent(request):
	if request.user.is_authenticated():
		if request.method == "POST":
			form = EventForm(request.POST)
			if form.is_valid():
				#print "its ok"
				username = request.user.username
				UserName = User.objects.get(username=username)
				tag = form.cleaned_data['Tag']
				description = form.cleaned_data['Description']
				#eventdate = form.cleaned_data['event_date']
				startdate = form.cleaned_data['start_date']
				enddate = form.cleaned_data['end_date']
				newEvent = Event(
					UserName = UserName ,
					Tag = tag, 
					Description = description,
					start_date = startdate,
					end_date = enddate)
				newEvent.save()
				######## just for verification 
				#context = {'UserNmae' : UserName, 'Tag' : tag, 'Note' : description,}
				#return render(request, 'printNote.html', context)
				return redirect('notes:allevents')
			else:
				form = EventForm()
				#return HttpResponse("Nope")
		return render(request, 'enterNote.html', {"form" : form})
	else:
		return redirect('login_logout:index')
# Editing a event
def editEventform(request, id):
	if request.user.is_authenticated():
		event = Event.objects.get(UserName=request.user,pk=id)
		form = EventDateEditForm(initial={'start_date' : event.start_date, 'end_date' : event.end_date})
		#return HttpResponse("success")
		return render(request, 'editEventform.html',  {"event" : event, "form" : form })
	else:
		return redirect('login_logout:index')	
# save edited note
def editEvent(request, id):
	if request.user.is_authenticated():
		if request.method == "POST":
			form = EventForm(request.POST)
			if form.is_valid():
				event = Event.objects.get(UserName=request.user,pk=id)
				event.Tag = form.cleaned_data['Tag']
				event.Description = form.cleaned_data['Description']
				#event.event_date = form.cleaned_data['event_date']
				event.start_date = form.cleaned_data['start_date']
				event.end_date = form.cleaned_data['end_date']
				#print date
				event.save()
				#context = {'Tag' : tag, 'Note' : note,}
				return render(request, 'index.html',)
			else:
				event = Event.objects.get(UserName=request.user,pk=id)
				form = EventDateEditForm(initial={'start_date' : event.start_date, 'end_date' : event.end_date})
		return render(request, 'editEventform.html',  {"event" : event, "form" : form })
	else:
		return redirect('login_logout:index')	
# Deleting a Note
def deleteEvent(request, id):
	if request.user.is_authenticated():
		Event.objects.get(UserName=request.user,pk=id).delete()
		return redirect('notes:allevents')
	else:
		return redirect('login_logout:index')
# Printing all events under the user
def allevents(request):
	if request.user.is_authenticated():
		events = Event.objects.filter(UserName=request.user).order_by('start_date')
		return render(request, 'allevents.html', {'events' : events})
	else:
		return redirect('login_logout:index')	
# Serch a tag given after URL : searchTag/"."

# Search Note using Tag from GET request(Partial search accepted)

################ FILE HANDELING ####################
########## Image Uploading #######
# used to create image form
def Image(request):
	if request.user.is_authenticated():
		form = ImageForm()
		return render(request, 'image.html', {'form':form})
	else:
		return redirect('login_logout:index')
# saving image and replying using HttpResponse
def Display(request):
	if request.user.is_authenticated():
		if request.method == "POST":
			form = ImageForm(request.POST, request.FILES)
			if form.is_valid():
				profile = Images()
				username = request.user.username
				user = User.objects.get(username=username)
				profile.UserName = user
				profile.Image_tag = form.cleaned_data["Image_tag"]
				profile.Image = form.cleaned_data["Image"]
				profile.save()
				#return render(request,'saved.html',)
				return HttpResponse("Saved Image")
			else:
				form = ImageForm()
		return render(request, 'image.html', {'form': form} )
	else:
		return redirect('login_logout:index')
##########################################
#
############ Doc Uploading ###############
# used to create doc upload form
def uploadDocument(request):
	docform = DocumentForm()
	return render(request, 'upload.html', {'form': docform } )
# saving a doc and redirecting for another upload
def saveDoc(request):
	# Handle file upload
	if request.user.is_authenticated():
		if request.method == 'POST':
			form = DocumentForm(request.POST, request.FILES)
			if form.is_valid():
				#print request.FILES['docfile'].
				#user = User.objects.get(username=request.user.username)
				newdoc = Document(UserName = request.user, docfile = request.FILES['docfile'])
				newdoc.save()
				savestatus = "Doc saved successfully. You can Procced further"
				form = DocumentForm()
				return render(request, 'upload.html', {'savestatus' : savestatus, 'form' : form})

g49/notes/templates/allevents.html
{% extends 'base.html' %}

{% block body%}
    
    <div class="row">
            <div class="col-sm-12">
                <h3>Your Events</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Tag</th>
                                    <th>Description</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr>
                                        <td>{{ event.Tag }}</td>
                                        <td>{{ event.Description | truncatechars:40}}</td>
                                        <td>{{ event.start_date }}</td>
                                        <td>{{ event.end_date }}</td>
                                        <td>
                                            <a href="{% url 'notes:deleteEvent' event.pk%}">
                                            <button type="button" class="btn btn-danger">
                                                Delete
                                            </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'notes:editEventform' event.pk %}">
                                            <button type="button" class="btn ">
                                                Edit
                                            </button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

g49/notes/templates/calendar.html
{% extends 'base.html' %}

{% block body%}
<div class="container-fluid">
  <div class="row" ">
    <div class="container-fluid col-xs-6" style="margin-bottom: 25px; border-style: solid;border-color: lightgrey;border-width: 1px; padding: 2px;">
      <a href="{% url 'notes:allevents' %}"><button type="button" class="btn btn-success">All Events</button></a>
    </div>
    <div class="container-fluid col-xs-6" style="margin-bottom: 25px; border-style: solid;border-color: lightgrey;border-width: 1px; padding: 2px;">
      <a href="{% url 'notes:enterevent'%}"><button type="button" class="btn btn-success">Add new Event</button></a>
    </div>
  </div>
</div>
<div class="container-fluid">   
  <div class="row">
       <div class="container-fluid col-xs-6 shadow" style="height: 700px; overflow: auto;">
       <h2>Calendar</h2>
       <div class="panel panel-default">
          <div class="panel-body">
           {{ calendar }}
          </div>
       </div>
       <a href="{% url 'notes:calendarof' year previous %}"><button type="button" class="btn btn-success" style="float:left;"><< Previous</button></a> 
       <a href="{% url 'notes:calendarof' year next %}"><button type="button" class="btn btn-success" style="float:right;">&nbsp;&nbsp; Next >> </button></a>
       </div>

       <div class="container-fluid col-xs-6 shadow" style="height: 700px; overflow: auto;">

       <h2 >Your Events</h2>
       	 {% if Event %}
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Event</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in Event %}
                                    <tr>
                                        <td>{{ event.event_date }}
                                        <h6>Start Date:{{event.start_date}}</h6>
                                        <h6>End Date:{{event.end_date}}</h6>
                                        </td>
                                        <td>{{ event.Tag }}
                                        <p>{{event.Description | truncatechars:30}}</p>
                                        <div style="float: left;">             
                                        <a href="{% url 'notes:editEventform' event.pk %}">
                                          <button>Edit Event</button>
                                        </a>
                                        </div>
                                        <div style="float: right";>
                                        <a href="{% url 'notes:deleteEvent' event.pk %}">
                                          <button>Delete Event</button>
                                        </a>
                                        </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% else %}

              <h3> Not any events for this Month!!!</h3>
              <a href="{% url 'notes:enterevent'%}"> Create one!!!</a>

           {% endif%} 



       </div>
  </div>
</div>
{% endblock %}

g49/notes/templates/editEventform.html
{%  extends 'base.html'%}

{% block body %}
        
        <form name = "form" action = "{% url 'notes:editEvent' event.pk %}"
         method = "POST" >{% csrf_token %}

                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <span class="text-danger small"></span>
                                        </div>
                                        <label class="control-label col-sm-2" value ="field."><label for="id_Tag">Tag:</label></label>
                                        <div class="col-sm-10" >
                                            <input id="id_Tag" maxlength="20" type="text" value = "{{ event.Tag }}" name="Tag" required />
                                        </div>
                                    </div>
                        
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <span class="text-danger small"></span>
                                        </div>
                                        <label class="control-label col-sm-2" value ="field."><label for="id_Note">Description:</label>
                                        </label>
                                        <div class="col-sm-10" >
                                            <textarea cols="70" id="id_Note" rows="10" 
                                            name="Description" required> {{ event.Description }}   
                                            </textarea>
                                        </div>
                                    </div>
                                         
                                {% for field in form %}
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <span class="text-danger small">{{ field.errors }}</span>
                                        </div>
                                        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
                                        <div class="col-sm-10">{{ field }}</div>
                                    </div>
                                {% endfor %}

                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
      </form>

{% endblock %}

g49/notes/templates/editNoteform.html
{%  extends 'base.html'%}

{% block body %}
        
        <form name = "form" action = "{% url 'notes:editNote' note.pk %}"
         method = "POST" >{% csrf_token %}

                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <span class="text-danger small"></span>
                                        </div>
                                        <label class="control-label col-sm-2" value ="field."><label for="id_Tag">Tag:</label></label>
                                        <div class="col-sm-10" >
                                            <input id="id_Tag" maxlength="20" type="text" value = "{{ note.Tag }}" name="Tag" required />
                                        </div>
                                    </div>
                        
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <span class="text-danger small"></span>
                                        </div>
                                        <label class="control-label col-sm-2" value ="field."><label for="id_Note">Note:</label>
                                        </label>
                                        <div class="col-sm-10" >
                                            <textarea cols="70" id="id_Note" rows="20" 
                                            name="Note" required> {{ note.Note }}   
                                            </textarea>
                                        </div>
                                    </div>        
                                    <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
      </form>

{% endblock %}

g49/notes/templates/listDocs.html
{%  extends 'base.html'%}

{% block body %}

    {% if docs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Your Documents</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th style="text-align: center;">Document Name</th>
                                    <th style="text-align: center;">Created Date</th>
                                    <th style="text-align: center;">File Type</th>
                                    <th style="text-align: center;">Size</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for document in docs %}
                                    <tr>
                                        <td style="border-color: lightgrey;">
                                            <a href="{{ document.docfile.url }}">{{ document.name }}
                                        </td>
                                        <td style="border-color: lightgrey;">
                                            {{ document.my_date }}
                                        </td>
                                        <td style="border-color: lightgrey;">
                                            {{ document.extension }}
                                        </td>
                                        <td style="border-color: lightgrey;">
                                            {{ document.docfile.size }} B
                                        </td>
                                        <td style="border-color: lightgrey;">
                                            <a href="{% url 'notes:deleteDoc' document.pk %}">
                                            <button type="button" class="btn btn-danger">
                                                Delete
                                            </button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container-fluid">
        <h2>No Documents!!</h2>
        <a href="{% url 'notes:upload' %}">
              <button type="button" class="btn btn-success">          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Documents
            </button>
        </a>
        </div>
    {% endif %}


{% endblock%}

g49/notes/templates/printNote.html
{% extends 'base.html' %}

{% block body%}
      
      <div class="container-fluid">
      	<div class="row">
      		<div class="container-fluid col-xs-6 shadow" style="width: 24%; margin: 3px; height: 600px;">
      			<h4>Date Created:</h4>{{ note.my_date}}
      			<h4>Modified Date:</h4>{{ note.modified_date}}
                        </br>
                        <div class="row" style="margin-top: 20px;">
                              <div class="container-fluid col-xs-6">
                                    <a href="{% url 'notes:editNoteform' note.pk %}"><button type="button" class="btn btn-success">Edit Note</button></a>
                              </div>
                              <div class="container-fluid col-xs-6" >
                                    <a href="{% url 'notes:deleteNote' note.pk %}" ><button type="button" class="btn btn-danger">Delete Note</button></a>
                              </div>
                        </div>
      		</div>
      		<div class="container-fluid col-xs-6 shadow" style="width: 75%; margin: 2px; height: 600px;">
      			<h3>{{ note.Tag}}</h3></br>
      			<p>{{ note.Note}}</p>
      		</div>
      	</div>
      </div>
{% endblock%}