g49/g49/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from login_logout.views import homepage
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login_logout/', include('login_logout.urls', namespace="login_logout")),
    url(r'^notes/', include('notes.urls',namespace="notes")),
    url(r'^$', homepage,name='homepage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

g49/login_logout/urls.py
from django.conf.urls import url
from . import views

app_name = "login_logout"

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$',views.register,name='register'),
	url(r'^registerform/$', views.register_form, name='register_form'),
	url(r'^login_user/$', views.login_user, name='login_user'),
	url(r'^logout_user/$', views.logout_user, name='logout_user'),
	url(r'^filluserdata/$',views.filluserdata, name='filluserdata'),
    url(r'^homepage/$',views.homepage,name='homepage'),
    url(r'^aboutme/$', views.aboutme,name='aboutme'),
]

g49/notes/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url(r'^hello/', views.hello, name='hello'),
    url(r'^enternoteform/', views.enterNoteform, name='enterNoteform'),
    url(r'^printNote/', views.enterNote, name='printNote'),
    url(r'^displaynote/(\d+)/', views.displayNote, name='displaynote'),
    #
    url(r'^searchTag/(\w+)/', views.searchTag, name = 'searchTag'),
    #
    url(r'^editNoteform/(\d+)/', views.editNoteform, name = 'editNoteform'),
    url(r'^editNote/(\d+)/', views.editNote, name = 'editNote'),
    url(r'^deleteNote/(\d+)/', views.deleteNote, name = 'deleteNote'),
    url(r'^searchNote/', views.searchNote, name='searchNote'),
    #url(r'^search/', views.search, name='search'),
    url(r'^alltags/', views.AllTags, name = 'AllTags'),
    #
    url(r'^image/', views.Image, name = 'Image'),
    url(r'^saved/', views.Display, name = 'Display'),
    #url(r'^saved/', views.saved, name = 'Display')
    url(r'^upload/', views.uploadDocument, name = 'upload'),
    url(r'^savedoc/', views.saveDoc, name='saveDoc'),
    url(r'^listdocs/$', views.listDocs, name='listdoc'),
    #
    url(r'^calendar/(\d+)/(\d+)', views.calendarof, name='calendarof'),
    url(r'^calendar/', views.calendar, name='calendar'),
    #
    url(r'^enterevent/', views.enterEventForm, name='enterevent'),
    url(r'^saveEvent/', views.saveEvent, name='saveEvent'),
    #
    url(r'^editEventform/(\d+)/', views.editEventform, name = 'editEventform'),
    url(r'^editEvent/(\d+)/', views.editEvent, name = 'editEvent'),
    url(r'^deletEvent/(\d+)/', views.deleteEvent, name = 'deleteEvent'),
    url(r'^allevents/', views.allevents, name='allevents'),
    #url(r'^searchNote/', views.searchNote, name='searchNote'),
    #
    url(r'^deleteDoc/(\d+)/', views.deleteDoc, name = 'deleteDoc'),
]

g49/login_logout/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
# Create your models here.

class UserInfo(models.Model):
	UserName = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	FullName = models.CharField(max_length=50)
	BirthDate = models.DateField()
	Email = models.EmailField(max_length=70,blank=False,unique=True)
	Gender = models.CharField(max_length=1)
	ProfilePic = models.ImageField(upload_to='ProfilePic/')
	Quote = models.CharField(max_length=200)

	def __str__(self):
		return self.FullName

g49/notes/models.py
from django.db import models
from login_logout.models import UserInfo
from django.db.models import ImageField, signals
from django.contrib.auth.models import Permission, User
##
from calendar import HTMLCalendar
from datetime import date
from itertools import groupby
from django.utils.html import conditional_escape as esc
from datetime import datetime, timedelta
import os
############## NOTES ################## 
class Notes(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Tag = models.CharField(max_length=20)
	Note = models.TextField()
	my_date = models.DateTimeField(default=datetime.now())
	modified_date = models.DateTimeField(default=datetime.now())

	def __str__(self):
		return self.UserName
############### EVents module ##########
class Event(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Tag = models.CharField(max_length=10)
	Description = models.TextField(max_length=100)
	#event_date = models.DateField()
	my_date = models.DateTimeField(default=datetime.now() + timedelta(days=1))
	start_date = models.DateField()
	end_date = models.DateField()

	def __str__(self):
		return self.UserName
################ FILE HANDELING ####################
class Images(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	Image_tag = models.CharField(max_length = 50)
	Image = models.ImageField(upload_to='images/')

	def __str__(self):
		return self.Image_tag
############### Document ###################
class Document(models.Model):
	UserName = models.ForeignKey(User, on_delete=models.CASCADE)
	docfile = models.FileField(upload_to='')
	#size =
	my_date = models.DateTimeField(default=datetime.now())
	modified_date = models.DateTimeField(default=datetime.now())
	#name, extension = (docfile.name).split(".")
	#name = docfile.name
	#extension = os.path.splitext(name)[1][1:]
	def extension(self):
		name, extension = os.path.splitext(self.docfile.name)
		return extension[1:]
	def name(self):
		name, extension = os.path.splitext(self.docfile.name)
		return name
	#def __str__(self):
	#	return self.docfile
################# HTML Calender #####################
class WorkoutCalendar(HTMLCalendar):
	def __init__(self, workouts):
		super(WorkoutCalendar, self).__init__()
		self.workouts = self.group_by_day(workouts)
	def formatday(self, day, weekday):
		if day != 0:
			cssclass = self.cssclasses[weekday]
			if date.today() == date(self.year, self.month, day):
				cssclass += ' today'
			if day in self.workouts:
				cssclass += ' filled'
				body = ['<ul>']
				for workout in self.workouts[day]:
					body.append('<li>')
					#body.append('<a href="%s">' % workout.get_absolute_url())
					body.append(esc(workout.Tag))
					body.append('</li>')
				body.append('</ul>')
				return self.day_cell(cssclass, '%d' % day)
			return self.day_cell(cssclass, day)
		return self.day_cell('noday', '&nbsp;')

	def formatmonth(self, year, month):
		self.year, self.month = year, month
		return super(WorkoutCalendar, self).formatmonth(year, month)

	def group_by_day(self, workouts):
		field = lambda workout: workout.start_date.day
		return dict(
			[(day, list(items)) for day, items in groupby(workouts, field)]
		)

	def day_cell(self, cssclass, body):
		return '<td class="%s">%s</td>' % (cssclass,body)

g49/login_logout/forms.py
from django import forms
from django.contrib.auth.models import User
import datetime
from django.forms.extras.widgets import SelectDateWidget
from .models import UserInfo

choice = (
	('M', 'M'),
	('F', 'F'),
	)
class DateInput(forms.DateInput):
    input_type = 'date'
    
class UserRegistrationForm(forms.ModelForm):
	Gender = forms.ChoiceField(choices=choice, required=True)
	#BirthDate = forms.DateField(widget=SelectDateWidget)
	class Meta:
		model = UserInfo
		fields = ['FullName' , 'ProfilePic', 'BirthDate' ]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    retype_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

g49/notes/forms.py
from django import forms
from django.contrib.auth.models import User
#from django.contrib.admin.widgets import AdminDateWidget
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.admin import widgets                                       


from .models import *

class Note(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['Tag', 'Note']
################ Event Form #################
class EventForm(forms.ModelForm):
    #event_date = forms.DateField(widget=SelectDateWidget)
    start_date = forms.DateField(widget=SelectDateWidget)
    end_date = forms.DateField(widget=SelectDateWidget)
    class Meta:
        model = Event
        fields = ['Tag', 'Description']
        #fields[2].widget = widgets.AdminSplitDateTime()

class EventDateEditForm(forms.Form):
    #event_date = forms.DateField(widget=SelectDateWidget)
    start_date = forms.DateField(widget=SelectDateWidget)
    end_date = forms.DateField(widget=SelectDateWidget)
    
    
################ FILE HANDELING ####################
class ImageForm(forms.ModelForm):
    class Meta:
       model = Images
       fields = ['Image_tag', 'Image']

class DocumentForm(forms.ModelForm):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )
    class Meta:
        model = Document
        fields = ['docfile']
           

g49/login_logout/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import UserInfo
from .forms import UserRegistrationForm,UserForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from notes.models import Notes,Event
from datetime import datetime
from django.shortcuts import render_to_response,redirect
# Create your views here.

def register(request):
    form = UserForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        retypepassword = form.cleaned_data['retype_password']
        if len(password) < 8:
            context = {
                "form" : form,
                "error_message" : "Password length should be grater than or equal to 8",
            }
            return render(request, 'register.html' , context)
        if password != retypepassword:
            context = {
                "form" : form,
                "error_message" : "Password and retype password are not equal",
            }
            return render(request, 'register.html' , context)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                regform = UserRegistrationForm()
                context = {
                	"form" : regform,
                	"username" : username,
                	"email" : email
                }
                return render(request, 'fillUserData.html', context)
    context = {
        "form": form,
    }
    return render(request, 'register.html', context)



def logout_user(request):
    logout(request)
    #form = UserForm(request.POST or None)
    #context = {
    #    "form": form,
    #}
    return render(request, 'homepage.html',)



def login_user(request):
        if request.user.is_authenticated():
            return redirect('login_logout:index')
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username , password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    email = request.user.email
                    user = User.objects.get(username=username)
                    ob = Notes.objects.filter(UserName = user)
                    today = datetime.now().date()
                    year = today.year
                    month = today.month
                    day = today.day

                    events = Event.objects.filter(UserName=request.user,start_date__day__gte=day,).exclude(
                        end_date__year__lte=year,
                        end_date__month__lte=month,
                        ).order_by('start_date')
                    return render(request, 'index.html', { "username" : username , "Notes" : ob, "Event" : events})
                    #return render(request, 'index.html' , { "username": username, "email" : email})
                else:
                    return render(request, 'login.html' , { "error_message" : "Username or Password is Incorrect!!!"})
            else:
                return render(request, 'login.html' , { "error_message" : "Username or Password is Incorrect!!!"})
        return render(request, 'login.html',)

def register_form(request):
    form = UserForm()
    return render(request, 'register.html', {"form" : form})


def filluserdata(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            form = UserRegistrationForm(request.POST, request.FILES)
            if form.is_valid():
                
                Username = request.user.username
                FullName = form.cleaned_data['FullName']
                BirthDate = form.cleaned_data['BirthDate']
                Gender = form.cleaned_data['Gender']
                Email = request.user.email
                ProfilePic = form.cleaned_data['ProfilePic']
                newUser = UserInfo(UserName = User.objects.get(username=Username), FullName = FullName, BirthDate = BirthDate, Email = Email, Gender = Gender, ProfilePic= ProfilePic)
                newUser.save()
                return render(request, 'index.html',)
            else:
                regform = UserRegistrationForm()
                context = {
                    "form" : regform,
                    "username" : request.user.username,
                    "email" : request.user.email,
                    "error_message" : "Form id invalid"
                }
                return render(request, 'fillUserData.html', context)
        return render(request, 'index.html',)
    else:
        return redirect('login_logout:register')

def index(request):
    if request.user.is_authenticated():
        username = request.user.username
        user = User.objects.get(username=username)
        ob = Notes.objects.filter(UserName = user)
        today = datetime.now().date()
        year = today.year
        month = today.month
        day = today.day
        
        events = Event.objects.order_by('start_date','my_date').filter(UserName=request.user).exclude(
            end_date__year__lte=year,
            end_date__month__lte=month,
            end_date__day__lt=day,
            )
        return render(request, 'index.html', { "username" : username , "Notes" : ob, 
            "Event" : events
            })
    else:
        return redirect('login_logout:login_user')

def homepage(request):
    return render(request,'homepage.html',)

def aboutme(request):
    if request.user.is_authenticated():
        me = UserInfo.objects.filter(UserName=request.user)
        return render(request,'aboutme.html',{"me" : me})
    else:
        return redirect('login_logout:login_user')

g49/login_logout/templates/aboutme.html
{% extends 'base.html' %}
{% block body %}
	<div>
		{% for x in me %}
			<h3>{{x.UserName}}</h3>
			<h3>{{x.FullName}}</h3>
			<h3>{{x.Gender}}</h3>
			<h3>{{x.BirthDate}}</h3>
			<h3>{{x.Email}}</h3>
		{% endfor%}
	</div>
{% endblock %}

g49/login_logout/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mynote{% endblock %}</title>
    {% load staticfiles %}
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'calendar.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'login_logout:index' %}">Mynote</a>
        </div>

        <!-- Items changes still to be done :url update to apropriate models-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block document_active %}{% endblock %}"><a href="{% url 'notes:listdoc'%}"><span class="filetypes filetypes-doc" aria-hidden="true"></span>&nbsp; Documents</a></li>
                <li class="{% block note_active %}{% endblock %}"><a href="{% url 'notes:AllTags'%}"><span class="glyphicons glyphicons-notes" aria-hidden="true"></span>&nbsp; Notes</a></li>
                <li class="{% block event_active %}{% endblock %}"><a href="{% url 'notes:calendar' %}"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp; Events</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'notes:searchNote' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'login_logout:aboutme' %}">
                        <span class="glyphicons glyphicons-user" aria-hidden="true"></span>&nbsp; About Me!
                    </a>
                </li> 
                <li>
                    <a href="{% url 'notes:upload' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Documents
                    </a>
                </li>
                <li>
                    <a href="{% url 'notes:enterNoteform' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Notes
                    </a>
                </li>
                <li>
                    <a href="{% url 'login_logout:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

g49/login_logout/templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mynote{% endblock %}</title>
    {% load staticfiles %}
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <!-- <script src="{% static 'music/js/main.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
      $( function() {
    $( "#id_BirthDate" ).datepicker();
  } );
  </script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           
        </div>

        

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

g49/login_logout/templates/document.html
hello docu

g49/login_logout/templates/event.html
hello event

g49/login_logout/templates/fillUserData.html
{% extends 'base_visitor.html' %}
{% block title %}Register{% endblock %}



{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Fill Your Personal Information</h3>
                    <!-- {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %} -->

                    {% if error_message %}
                        <p style="color:red;"><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    
                    <p><strong>Username : {{username}}</strong></p> 
                    <p><strong>Email : {{email}}</strong></p>
                    <form class="form-horizontal" role="form" action="{% url 'login_logout:filluserdata' %}" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
							    {% for field in form %}
							    	<div class="form-group">
							        	<div class="col-sm-offset-2 col-sm-10">
							            	<span class="text-danger small">{{ field.errors }}</span>
							        	</div>
							        	<label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
							        	<div class="col-sm-10">{{ field }}</div>
							    	</div>
								{% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- <div class="panel-footer">
                    Already have an account? <a href="{% url 'login_logout:login_user' %}">Click here</a> to log in.
                </div> -->
            </div>
        </div>
    </div>

</div>

{% endblock %}

g49/login_logout/templates/homepage.html
{% extends 'base_visitor.html' %}
{%  block body %}	
		<div class="container-fluid">
			

			<h1 style="font-size: 20em; color: #4286f4; text-align:center; margin-bottom:50px;">MyNote</h1>
			<hr >
			<div class="row">
				<div class="container-fluid col-xs-6" style="text-align:center;">
					<a href="{% url 'login_logout:register' %}"><div class="shadow" style="background-color:white; border-style:solid; border-color: grey; border-radius: 5px; border-width:1px; height: 100px;"><h3>Sign Up!!</h3>
					<h5>Create a free user account here!!</h5></div></a>
				</div>
				<div class="container-fluid col-xs-6" style="text-align:center;">
					<a href="{% url 'login_logout:login_user' %}"><div class="shadow" style="background-color:white; border-style:solid; border-color: grey; border-radius: 5px; border-width:1px; height: 100px;"><h1>Login!!</h1></div></a>
				</div>
				</div>
			</div>
{% endblock %}

g49/login_logout/templates/index.html
{% extends 'base.html' %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-xs-6 container-fluid" style="width:75%;">
        <h3>{{ request.user.username }}'s Notes</h3>
            {% if Notes %}
            {% for note in Notes %}
                <div class="col-sm-4">
                    <a href="{% url 'notes:displaynote' note.pk %}" >
                    <div class="thumbnail">
                        <div class="caption" style="display: block; text-align: center;">
                            <h5>{{ note.Tag }}</h5>
                            <!-- <h4>{{ note.Note }}</h4> -->
                        </div>
                    </div></a>
                </div>
                
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'notes:enterNoteform' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Note
                    </button>
                </a>
            </div>
        {% endif %}
        </div>

        <div class="col-xs-6 container-fluid" style="width : 24%;">

            {% if Event %}
            <h3 style="text-align: center;">Upcoming Events</h3>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table" style="border-style: none;">
                            <thead style="border-style: none;">
                                <tr style="border-style: none;">
                                    <th style="border-style: none; text-align: center;">Date</th>
                                    <th style="border-style: none; text-align: center;">Event</th>
                                </tr>
                            </thead>
                            <tbody style="border-style: none;">
                                {% for event in Event %}
                                    <tr style="border-style: none;" class="shadow-down">
                                        <td style="border-style: none;">{{ event.start_date }}</br> to </br>{{ event.end_date }}
                                        </td>
                                        <td style="border-style: none;">{{ event.Tag }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% else %}

              <h3 style="text-align: center;"> No Upcoming events!!!</h3>
              <h4 style="text-align: center;"><a href="{% url 'notes:enterevent' %}"> Create one!!!</a></h4>

           {% endif%} 


        </div> 

        
    </div>
</div>
{% endblock %}

g49/login_logout/templates/note.html
{% extends 'base.html' %}

{% block body%}
	{% if notes %}
    	<div class="row">
                <div class="col-sm-12">
                    <h3>Your Notes</h3>
                </div>
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <table class="table" style="border-style:none;">
                                <thead style="border-style:none;">
                                    <tr style="border-style:none;">
                                        <th style="text-align: center;">Tag</th>
                                        <th style="text-align: center;">Note</th>
                                        <th style="text-align: center;">Created Date</th>
                                        <th style="text-align: center;">Last Modified</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for note in notes %}
                                        <tr style="border-style:none; margin: auto; width: 15px;">
                                            <td style="border-color: lightgrey;"><a href="{% url 'notes:displaynote' note.pk %}"><div>{{ note.Tag }}</div></a></td> 
                                            <td style="border-color: lightgrey;">{{ note.Note | truncatechars:40 }}</td>
                                            <td style="border-color: lightgrey;">{{ note.my_date }}</td>
                                            <td style="border-color: lightgrey;">{{ note.modified_date }}</td>
                                            <td style="border-color: lightgrey;">
                                                <a href="{% url 'notes:deleteNote' note.pk %}">
                                                <button type="button" class="btn btn-danger">
                                                    Delete
                                                </button>
                                                </a>
                                            </td>
                                            <td style="border-color: lightgrey;">
                                                <a href="{% url 'notes:editNoteform' note.pk %}">
                                                <button type="button" class="btn ">
                                                    Edit
                                                </button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    }
    {% else %}
        <div class="col-sm-12">
                <br>
                <a href="{% url 'notes:enterNoteform' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Note
                    </button>
                </a>
            </div>

    {% endif %}
{% endblock %}